### ISSUE TITLE
go get failed

### ISSUE THREAD

**Issue by wehtta** [gographics/imagick#33]
/usr/bin/ld: skipping incompatible /usr/local/lib/libMagickWand-6.Q16.so when searching for -lMagickWand-6.Q16
/usr/bin/ld: skipping incompatible /usr/local/lib/libMagickWand-6.Q16.a when searching for -lMagickWand-6.Q16
/usr/bin/ld: skipping incompatible //usr/local/lib/libMagickWand-6.Q16.so when searching for -lMagickWand-6.Q16
/usr/bin/ld: skipping incompatible //usr/local/lib/libMagickWand-6.Q16.a when searching for -lMagickWand-6.Q16
/usr/bin/ld: cannot find -lMagickWand-6.Q16
/usr/bin/ld: skipping incompatible /usr/local/lib/libMagickCore-6.Q16.so when searching for -lMagickCore-6.Q16
/usr/bin/ld: skipping incompatible /usr/local/lib/libMagickCore-6.Q16.a when searching for -lMagickCore-6.Q16
/usr/bin/ld: skipping incompatible //usr/local/lib/libMagickCore-6.Q16.so when searching for -lMagickCore-6.Q16
/usr/bin/ld: skipping incompatible //usr/local/lib/libMagickCore-6.Q16.a when searching for -lMagickCore-6.Q16
/usr/bin/ld: cannot find -lMagickCore-6.Q16
collect2: error: ld returned 1 exit status

**Comment by justinfx** [comment]
This means you do not have ImageMagick installed in a standard system
location with an available pkg-config file.
Where is your ImageMagick installed? You may need to download this library
and build it, while pointing it at your ImageMagick install location.

**Comment by justinfx** [comment]
Also, have you followed the instructions listed in the readme?

**Comment by wehtta** [comment]
@justinfx   Actually, I manually find the libs. And the output said incompatible, other than not find. I tried this on Linux system. I do not know if anybody successfully installed this package.

**Comment by justinfx** [comment]
Many people successfully install this package. So lets just focus on your particular configuration issue. 
Which version of ImageMagick have you installed, and where is it located? In the README, it says the package is tested up to ImageMagick 6.8.x. Maybe you are using too old or too new of a version?

**Comment by justinfx** [comment]
I've just tested building against both ImageMagick 6.8 and 6.9 versions, and side from some deprecated functions (which are addressed in another ticket), they all should work fine. You might want to try reinstalling your ImageMagick version, as something about the linker doesn't like how they are built.

**Comment by wehtta** [comment]
@justinfx , Firstly, I tried it OSX with latest version, failed. Then I tried on linux, still failed. The linux was previously installed with 6.9.0. Then I remove the libs, reinstalled with 6.8.4, still failed. If people can successfully install it, I think it may be caused by not clean all the old-version files. 

Thank you for your answer. I will try again.

**Comment by justinfx** [comment]
It would have to be the case of old files, because I have built it three
times, on osx (mavericks) , against 6.8.5, 6.8.9, and 6.9.1.

Honesty it isn't a fluke that some people can randomly succeed in getting
this to build. It is something specific here in your env. If I can build it
on multiple ImageMagick versions, on osx and Linux, it must be working.

**Comment by wehtta** [comment]
@justinfx  My OSX kernel is Darwin apples-MacBook-Pro.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

Today , I tried to install on OSX, reporting 
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

while  run pkg-config --cflags --libs MagickWand, output
-DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/opt/local/include/ImageMagick-6 -L/opt/local/lib -lMagickWand-6.Q16 -lMagickCore-6.Q16

The libs and include files are exist.

**Comment by justinfx** [comment]
Is that an ImageMagick install via macports? That output suggests that you
have an x86_64 only build of ImageMagick, and the linker is trying to look
for a i386 build. I've used the homebrew install of ImageMagick on OSX,
without any trouble.  Maybe try reinstalling ImageMagick with whatever
flags ports makes available, to build fat binaries (i386, x86_64)

**Comment by wehtta** [comment]
@justinfx , Build fat binaries, the problem is solved.

Thanks so much !!

**Comment by justinfx** [comment]
Excellent. Glad we were able to solve the problem!
